heat_template_version: 2014-10-16

description: |
    Webhook triggered autoscaling group for Docker cluster

parameters:

    key_name:
        type: string
        label: Key Name
        description: Name of the server access key.

    docker_swarm_manager:
        type: string
        label: Swarm Manager
        description: Docker swarm manager.

    docker_swarm_token:
        type: string
        label: Swarm Token
        description: Token required to join an existing docker swarm.

resources:

    workers:
        type: Rackspace::AutoScale::Group
        properties:
            groupConfiguration:
                name: { get_param: "OS::stack_name" }
                metadata:
                    rax-heat: { get_param: "OS::stack_id" }
                maxEntities: 5
                minEntities: 2
                cooldown: 120
            launchConfiguration:
                type: launch_stack
                args:
                    stack:
                        template_url: https://raw.githubusercontent.com/m4dcoder/devstacks/master/openstack/heat/docker_worker.yaml
                        disable_rollback: False
                        parameters:
                            key_name: { get_param: key_name }
                            docker_swarm_manager: { get_param: docker_swarm_manager }
                            docker_swarm_token: { get_param: docker_swarm_token }
                        timeout_mins: 30

    scale_up_policy:
        type: Rackspace::AutoScale::ScalingPolicy
        properties:
            group: { get_resource: workers }
            name:
                str_replace:
                    template: stack scale up policy
                    params:
                        stack: { get_param: "OS::stack_name" }
            change: 1
            cooldown: 600
            type: webhook

    scale_up_webhook:
        type: Rackspace::AutoScale::WebHook
        properties:
            name:
                str_replace:
                    template: stack scale up hook
                    params:
                        stack: { get_param: "OS::stack_name" }
            policy: { get_resource: scale_up_policy }

    scale_down_policy:
        type: Rackspace::AutoScale::ScalingPolicy
        properties:
            group: { get_resource: workers }
            name:
                str_replace:
                    template: stack scale down policy
                    params:
                        stack: { get_param: "OS::stack_name" }
            change: -1
            cooldown: 600
            type: webhook

    scale_down_webhook:
        type: Rackspace::AutoScale::WebHook
        properties:
            name:
                str_replace:
                    template: stack scale down hook
                    params:
                        stack: { get_param: "OS::stack_name" }
            policy: { get_resource: scale_down_policy }

outputs:

    "Scale Up Webhook":
        value: { get_attr: [ scale_up_webhook, executeUrl ] }
        description: Scale Up Webhook

    "Scale Down Webhook":
        value: { get_attr: [ scale_down_webhook, executeUrl ] }
        description: Scale Down Webhook
